# Generated by Django 4.1.7 on 2023-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_remove_feedback_text_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
